### ISSUE TITLE
assoc_unix_epoch feature no longer needed

### ISSUE THREAD

**Issue by oefd** [riker-rs/riker#30]
The `#![feature(assoc_unix_epoch)]` is no longer required as it's now stabilized. Also incidentally: riker 0.1.8 compiles for stable rust just fine with that line removed.

**Comment by leenozara** [comment]
Hi Terry, thanks for bringing this to my attention. It has been removed in 0.1.9 soon to be released. 0.1.9 however requires `nightly` since it includes `async/await` support. After you mentioning this I might remove this feature from the current `0.1.8` and publish that as `0.1.9` which provides support for `stable`. Then make 0.2.0 the major version supporting `async/await`.

Or you could fork, remove it, and push a PR - then you'd be listed as a contributor :)

I greatly appreciate your message. Thank you.

**Comment by oefd** [comment]
There's a PR for you :)

Glad to hear `0.1.9` is coming soon (Or `0.2.0` as the case may be)!
