### ISSUE TITLE
Did you guys borrow community akka's design and codes to save much of time?

### ISSUE THREAD

**Issue by Kiddinglife** [riker-rs/riker#48]

**Comment by leenozara** [comment]
Myself, Mike and others that work on Riker have used Akka since the early days of Akka. Some of the principles around actor hierarchy and supervision were based on Akka. Much of the terminology is the same too, e.g. `Actor`, `ActorSystem`, `Context`, `ActorCell`, etc. The code however is not inspired by Akka since Scala and Rust are fundamentally different.

We know the Akka team and probably the time we've been able to save is from challenges the team have had to overcome in large scale deployments using clustering and persistence.

**Comment by Kiddinglife** [comment]
Thanks for your reply. Close it now.
